### ISSUE TITLE
please correct this letter on website 

### ISSUE THREAD

**Issue by mehrdad2** [negareh/felezgostaran#1]
![e66822ec-efb8-41cb-ac81-bd75a437b3ed](https://user-images.githubusercontent.com/4264683/50377832-9ee1a000-0639-11e9-800c-bb5e77c5a8a6.jpg)
![716efd92-eb70-4308-8469-ad55d84a8189](https://user-images.githubusercontent.com/4264683/50377833-9f7a3680-0639-11e9-9798-2b76b193b02b.jpg)

**Comment by shimafaraji** [comment]
Done
